### ISSUE TITLE
`RESQUE_PRE_SHUTDOWN_TIMEOUT` may be ignored

### ISSUE THREAD

**Issue by jiikko** [resque/resque-heroku-signals#13]
When a worker process receives a second TERM signal, it forcibly terminates the job. However, recent versions of Heroku may send multiple TERM signals, which means that the sender of the second TERM signal to the worker process may be the Heroku platform. According to this document (https://devcenter.heroku.com/articles/dynos#shutdown), it is possible that processes in a dyno that is being shut down may receive multiple SIGTERMs.

If the sender of the second TERM signal to the worker process is the Heroku platform, RESQUE_PRE_SHUTDOWN_TIMEOUT may be ignored and the job may be forcibly terminated before the timeout specified in RESQUE_PRE_SHUTDOWN_TIMEOUT.

thanks.

\<EDIT>
https://github.com/resque/resque/issues/1868

**Comment by iloveitaly** [comment]
I don't have time to make any improvements on this gem (I'm not actively using it and it's not sponsored), submit a PR and I'm happy to review!

**Comment by fxn** [comment]
I have a working patch in which I also change Resque to send `SIGINT` to the child, which greately simplifies the logic in the signal handler. Let me prepare a PR.
