### ISSUE TITLE
resque 2.1.0?

### ISSUE THREAD

**Issue by jrochkind** [resque/resque-heroku-signals#6]
Resque 2.1.0 is out! https://rubygems.org/gems/resque

Is this gem obsolete, and no longer needed with resque 2.1.0?  (in which case README could say so). 

Or, does it need to be updated to allow Resque 2.1.0 (after confirmation/possible alteration)?

**Comment by iloveitaly** [comment]
This is still required. Just cut a new release.

**Comment by jrochkind** [comment]
Thanks @iloveitaly !

With the newfound movement in resque, how feasible do you think it is to get this into resque so it doesn't require the third-party patch?

**Comment by iloveitaly** [comment]
> With the newfound movement in resque, how feasible do you think it is to get this into resque so it doesn't require the third-party patch?

I don't think it makes sense. This only applies to heroku environments, so we wouldn't want this to be the default behavior.

**Comment by jrochkind** [comment]
Oh, ok, I guess I don't really understand what's going on,that heroku was requiring special behavior nobody else would want, that's unfortunate on heroku's end. (I don't understand why other activejob backends like sidekiq or delayed_job don't need custom heroku patches though?)

Could it make sense to make it configurable in resque?  Requiring a separate patch that has to be kept in sync/checked on every resque release just seems unfortunate. 

RESQUE_PRE_SHUTDOWN_TIMEOUT and RESQUE_TERM_TIMEOUT seem like generally applicable features maybe?

Heroku definitely isn't the only platform where people want the behavior to "stop taking new jobs but wait X seconds for existing jobs to finish before interupting them", no?

**Comment by mmarinaccio** [comment]
@jrochkind I totally agree. I'm currently working on an AWS Fargate/Resque implementation and I'm running into the same problem.

AWS docs for container shutdown process:
https://aws.amazon.com/blogs/containers/graceful-shutdowns-with-ecs/

As far as I can tell, this is a fairly standard approach to cycling out resources in ephemeral environments.

@iloveitaly I think there's a strong case to be made for extending core Resque to support different signal patterns. This could provide a big step up in compatibility with modern ephemeral compute solutions like AWS Fargate. I'm happy to support or continue the conversation if you'd think it'd be useful.

**Comment by iloveitaly** [comment]
@mmarinaccio How does AWS fargate differ from the heroku signal patterns?

I'm not opposed to pulling this into resque master, but I'd like to learn more about how other platforms handle this so we create a solution that can be easily molded to fit other environments.

**Comment by mmarinaccio** [comment]
@iloveitaly I really appreciate your prompt response. I'll put something together to answer your question soon. I'm in the middle of validating my understanding of Fargate and how it interacts with Resque currently. More to come.

**Comment by mmarinaccio** [comment]
@iloveitaly Ok - I finally have more to add here. I have a working sandbox environment in my organization, where I leverage the `resque-heroku-signals` gem.

In short, the signal patterns are the same. ECS/Fargate sends a `SIGTERM`, and after some delay - defined on the ECS side as a max of 2 minutes - a `SIGKILL` signal is sent. This gem handles that perfectly.

So in terms of merging this into resque master, it might be as simple as replacing all _heroku_ references with more general terminology. One idea is to rebrand this functionality as a _shutdown strategy_, where the default is _immediate kill_ and the new option is _delayed kill_, or something like that.

Please let me know if you have any other questions. I'm happy to collaborate in whatever capacity you find helpful.
